stages:
  - lint
  - deploy

cathe: 
  key: 
    files:
      - package-lock.json
  path:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline


eslint: 
  stage: lint
  image: node:20-alpine
  script:
    - npm ci
    - npm run lint
