stages:
  - lint

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: lint
  image: node:20-alpine
  script:
    - npm install
    - npm run lint

format:
  stage: lint
  image: node:20-alpine
  script:
    - npm install
    - npm run format

test:
  stage: lint
  image: node:20-alpine
  script:
    - npm install
    - npm run test
