name: eslint

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: node:20-alpine
    steps:
      - uses: actions/checkout@v2
      - name: install node.js
        run: npm ci 
      - name: start lint
        run: npm run lint
  
             