name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    container:
      image: node:20-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: npm-${{ hashFiles('package-lock.json')}}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-key: |
            ${{ env.cache-name }}

      - name: install node.js
        run: npm ci
      - name: start build
        run: npm run build
