name: Deploy
on: 
  push:
    branches:
      - main

env:
  SERVER_HOST: winter-website.ru
  SERVER_USER: root
  SERVER_PATH: /root/TEST

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps: 
          - uses: actions/checkout@v4

          - name: Install SSH
            uses: shimataro/ssh-key-action@v2.3.1
            with: 
              key: "${{ secrets.INDEX_KEY }}"
              known_hosts: unnecessary
          
          - name: Generate auth hosts
            run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
            
            
          - run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
            
             