name: Test Nest App
on: push
jobs:
    test:
        runs-on: ubuntu-20.04
        steps: 
            - name: Get the repository
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Test app
              run: npm run test