name: Test Nest App
on: push
jobs:
    runs-on: ubuntu-20.04
    steps: 
        - name: Get the repository
        uses: actions/checkout@v3
        - name: install dependecies
        run: npm ci
        - name: Test app
        run: npm run test


